// Badge definitions for the achievement system
export const BADGE_DEFINITIONS = [
    {
        code: 'FIRST_REPORT',
        name: 'Premier Rapport',
        description: 'Soumettre votre premier rapport quotidien',
        icon: '📋',
        category: 'milestone',
        threshold: 1,
    },
    {
        code: 'STREAK_5',
        name: 'Flamme de 5 Jours',
        description: 'Soumettre des rapports pendant 5 jours consécutifs',
        icon: '🔥',
        category: 'streak',
        threshold: 5,
    },
    {
        code: 'STREAK_10',
        name: 'Flamme Inextinguible',
        description: 'Soumettre des rapports pendant 10 jours consécutifs',
        icon: '🔥',
        category: 'streak',
        threshold: 10,
    },
    {
        code: 'PERFECT_WEEK',
        name: 'Semaine Parfaite',
        description: 'Atteindre 100% de rendement sur une semaine',
        icon: '⭐',
        category: 'performance',
        threshold: 1,
    },
    {
        code: 'PLANS_10',
        name: 'Planificateur',
        description: 'Créer 10 plans hebdomadaires',
        icon: '📊',
        category: 'milestone',
        threshold: 10,
    },
    {
        code: 'EFFICIENCY_90',
        name: 'Haute Performance',
        description: 'Maintenir un rendement moyen supérieur à 90%',
        icon: '🎯',
        category: 'performance',
        threshold: 90,
    },
    {
        code: 'LEVEL_5',
        name: 'Vétéran',
        description: 'Atteindre le niveau 5',
        icon: '🏆',
        category: 'milestone',
        threshold: 5,
    },
    {
        code: 'LEVEL_10',
        name: 'Maître Artisan',
        description: 'Atteindre le niveau 10',
        icon: '👑',
        category: 'milestone',
        threshold: 10,
    },
    {
        code: 'EARLY_BIRD',
        name: 'Lève-Tôt',
        description: 'Soumettre un rapport avant 8h du matin',
        icon: '🌅',
        category: 'performance',
        threshold: 1,
    },
    {
        code: 'TEAM_PLAYER',
        name: 'Esprit d\'Équipe',
        description: 'Travailler sur 3 projets différents',
        icon: '🤝',
        category: 'milestone',
        threshold: 3,
    },
    {
        code: 'OVERTIME_HERO',
        name: 'Héros du Dépassement',
        description: 'Réaliser 150% de l\'objectif hebdomadaire',
        icon: '💪',
        category: 'performance',
        threshold: 150,
    },
    {
        code: 'CONSISTENT',
        name: 'Constance',
        description: 'Maintenir un rendement entre 95-105% pendant 4 semaines',
        icon: '📐',
        category: 'performance',
        threshold: 4,
    },
];
