"use client";

import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "fr" | "en" | "nl";

interface Dictionary {
  [key: string]: string;
}

const dictionaries: Record<Language, Dictionary> = {
  fr: {
    "login": "Connexion",
    "get_started": "Commencer",
    "dashboard": "Tableau de bord",
    "unassigned": "Non assigné",
    "global_budget_progress": "Progression Globale du Budget",
    "total_scheduled_labor": "Heures de Main-d'œuvre Planifiées",
    "achieved_labor_value": "Heures de Main-d'œuvre Réalisées",
    "tasks_tracked": "Tâches Suivies",
    "completed": "Terminé",
    "weekly_reports": "Rapports Hebdomadaires",
    "no_weekly_reports": "Le Chef de Chantier n'a pas encore soumis de plans ou rapports hebdomadaires.",
    "week": "Semaine",
    "workers_setup": "Équipe",
    "total_hrs": "hrs au total",
    "in_progress": "En cours",
    "target_hit": "Objectif Atteint",
    "target_missed": "Objectif Manqué",
    "reported_issues": "Problèmes Signalés",
    "no_issues": "Aucun problème signalé.",
    "scheduled_tasks": "Tâches Planifiées",
    "planned": "Planifié",
    "done": "Réalisé",
    "active_projects": "Projets Actifs",
    "submitted_plans": "Plans Hebdomadaires Soumis",
    "your_sites": "Vos Chantiers",
    "site_manager": "Chef de Chantier",
    "location": "Emplacement",
    "tasks_loaded": "Tâches chargées",
    "view_details": "Voir Détails",
    "delete": "Supprimer",
    "no_projects": "Aucun projet configuré pour le moment.",
    "new_project": "Nouveau Projet (Upload Excel)",
    "upload_in_progress": "Upload en cours...",
    "global_progress": "Progression Globale",
    "efficiency_progression": "Progression Efficience",
    "hour_distribution": "Répartition des Heures",
    "all_weeks": "Toutes les semaines",
    "weeks_4": "4 Semaines",
    "weeks_8": "8 Semaines",
    "weeks_12": "12 Semaines",
    "executed": "Exécuté",
    "display": "Affichage",
    "welcome": "Bienvenue",
    "hours": "h",
    "special_works": "TRAVAUX TECHNIQUES SPÉCIALES",
    "category": "Catégorie",
    "unit": "Unité",
    "quantity": "Quantité",
    "cable": "Câble",
    "tube": "Tube d'attente",
    "lighting": "Eclairage",
    "primary_pipes": "Canalisations primaires",
    "electrical_panels": "Tableaux électriques",
    "others": "Autres",
    "last_revision": "Dernière révision",
    "created": "créés",
    "updated": "mis à jour",
    "cancelled": "annulés",
    "empty_drums": "Tourets vides (Consignations) à récupérer",
    "category_heatmap": "Productivité par Catégorie (Heatmap)",
    "efficiency_delta": "Efficience par Catégorie (%)",
    "missed_reason_select": "Raison de l'objectif manqué",
    "MATERIAL_DELAY": "Retard Matériel",
    "WEATHER": "Météo",
    "EQUIPMENT_FAILURE": "Panne d'Équipement",
    "LABOR_SHORTAGE": "Manque de Main-d'œuvre",
    "PLANNING_ERROR": "Erreur de Planification",
    "OTHER": "Autre",
    "user_not_found": "Utilisateur introuvable",
    "global_status": "Statut Global",
    "active_sites": "Chantiers Actifs",
    "total_tasks": "Tâches Total",
    "assigned_tasks": "Tâches assignées",
    "on_site": "Sur site",
    "view_analytics": "Voir Analyses",
    "enter_daily_report": "Saisir le rapport du jour",
    "view_planning": "Voir le planning",
    "manage_teams": "Gérer les équipes",
    "no_assigned_sites": "Vous n'êtes assigné à aucun chantier pour le moment.",
    "contact_pm": "Veuillez contacter votre Chef de Projet.",
    "recent_alerts": "Alertes Récentes",
    "offline_sync_pending": "Synchronisation hors ligne en attente",
    "offline_sync_reports": "rapports",
    "connect_to_network": "Connectez-vous au réseau.",
    "check": "Vérifier",
    "sm_analytics_title": "Analyses (Chef de Chantier)",
    "my_statistics": "Mes Statistiques",
    "statistics_overview": "Aperçu de la progression de vos chantiers assignés.",
    "projects_progress_hours": "Progression des Chantiers (Heures)",
    "benchmarking_title": "Classement Inter-Chantiers (Benchmarking)",
    "benchmarking_desc": "Comparez l'efficacité globale de vos chantiers avec le reste du parc (anonymisé).",
    "back": "Retour",
    "loading": "Chargement...",
    "plan_next_week_title": "Planifier la Semaine Prochaine",
    "plan_next_week_desc": "Définissez votre main-d'œuvre et sélectionnez les tâches avec leurs localisations.",
    "workforce_availability": "Disponibilité de la Main-d'œuvre",
    "available_workers_count": "Nombre de travailleurs dispo",
    "target_100": "Objectif (100%)",
    "tasks_catalog": "Catalogue des Tâches",
    "uncategorized": "Non Catégorisé",
    "lines_pl": "lignes",
    "remaining_pl": "restants",
    "back_to_categories": "Retour aux Catégories",
    "search_in": "Rechercher dans",
    "remaining_label": "Restant :",
    "remaining": "Restant",
    "line_label": "Ligne",
    "remains": "Reste",
    "add_to_plan": "Ajouter au Plan",
    "weekly_cart": "Panier de la Semaine",
    "currently_planned": "Actuellement Planifié :",
    "empty_plan_msg": "Votre plan est vide. Ajoutez des tâches depuis le catalogue.",
    "qty_to_do": "Qté à faire:",
    "locations_up_to_4": "Localisations (jusqu'à 4 menus) :",
    "none": "-- Aucun --",
    "materials_forecast": "Prévision des Matériaux",
    "validation_checklist": "Checklist de validation",
    "ready": "Prêt",
    "materials_ok": "Matériaux OK",
    "tools_ok": "Outils OK",
    "subcontractors": "Sous-traitants",
    "validate_and_save_plan": "Valider et Enregistrer le Plan",
    "network_restored": "Réseau rétabli. Rapports synchronisés avec succès.",
    "offline_mode_detected": "Mode hors-ligne détecté. Sauvegardé localement.",
    "checking_db": "Vérification de la base de données...",
    "no_active_plan": "Aucun plan actif",
    "no_active_plan_desc": "Vous n'avez aucun plan actif prévu pour ce projet cette semaine.",
    "daily_report_title": "Rapport Journalier",
    "offline_badge": "HORS-LIGNE",
    "daily_report_desc": "Validations de terrain, photos et saisie des objectifs atteints.",
    "planned_target": "Cible Prévue",
    "achieved": "Réalisé",
    "recorded_activity": "Activité Enregistrée",
    "planned_qty_var": "Prévu : ",
    "execution_locations": "Localisations d'exécution :",
    "issues_observations": "Problèmes & Observations",
    "target_missed_categorize": "L'objectif n'est pas atteint. Veuillez catégoriser la cause :",
    "select_rca_cause": "-- Sélectionner une cause (RCA) --",
    "detailed_desc_optional": "Description détaillée (Optionnel) :",
    "workforce_count_label": "Nombre de personnes",
    "workforce_count_desc": "Indiquez le nombre de personnes ayant travaillé aujourd'hui.",
    "add_unplanned_task": "Ajouter une tâche non planifiée",
    "select_category": "Sélectionnez une catégorie",
    "select_task": "Sélectionnez une tâche",
    "add_btn": "Ajouter",
    "non_planifie_badge": "Non Planifié",
    "problem_details_placeholder": "Détails du problème (ex: manque de matériel à l'étage 2)...",
    "empty_drums_title": "Consignations (Toupins)",
    "empty_drums_desc": "Indiquez les tourets vides de câbles prêts à la récupération.",
    "empty_drums_label": "Tourets vides :",
    "cancel": "Annuler",
    "save_locally": "Sauvegarder Localement",
    "submit_report": "Soumettre le Rapport",
    "project_manager": "Chef de Projet",
    "supervision_desc": "Supervision de l'ensemble des installations, des équipes sur site et suivis budgétaires.",
    "upload_xls": "Téléverser Plan XLS",
    "alerts_count": "alertes",
    "portfolio_performance": "Performances Portefeuille",
    "portfolio_analysis_desc": "Analyse approfondie de la productivité et des causes de retard sur l'ensemble de vos chantiers.",
    "overall_efficiency": "Efficacité Globale",
    "ratio_actual_planned": "Ratio réalisé vs prévu",
    "cumulative_value": "Valeur cumulée",
    "reported_rca": "RCA Signalés",
    "categorized_deviations": "Écarts catégorisés",
    "under_your_supervision": "Sous votre supervision",
    "projects_progress_pm": "Progression des Projets",
    "progress_comparison_desc": "Comparaison des heures planifiées vs exécutées.",
    "efficiency_by_category": "Efficacité par Catégorie Métier",
    "cross_project_analysis_desc": "Analyse croisée de la productivité sur tout le parc.",
    "evm_desc": "Évolution cumulée de la valeur planifiée (PV), acquise (EV) et des heures brûlées (AC).",
    "no_evm_data": "Aucune donnée EVM disponible.",
    "rca_analysis": "Analyse des Causes (RCA)",
    "recent_field_reports": "Signalements Récents du Terrain",
    "no_recent_issues": "Aucun problème signalé récemment.",
    "evm_title": "Earned Value Management (EVM)",
    "rca_title": "Analyse des Causes (RCA)",
    "recent_reports_title": "Signalements Récents du Terrain",
    "project_field": "Projet :",
    "no_evm_data_available": "Aucune donnée EVM disponible.",
    "upload_xls_title": "Créer un Nouveau Projet & Téléverser le Budget",
    "upload_xls_desc": "Remplissez les détails du projet et téléversez le fichier Excel 'Bordereau de prix' pour générer la liste des tâches.",
    "success_project_created": "Projet Créé avec Succès !",
    "parsing_redirect": "Données analysées, redirection vers le tableau de bord...",
    "project_name_label": "Nom du Projet *",
    "project_name_placeholder": "ex: Complexe de Bureaux",
    "site_manager_placeholder": "Sélectionner un Conducteur de Travaux",
    "start_date_label": "Date de Début",
    "end_date_label": "Date de Fin",
    "primary_location_label": "Lieu Principal",
    "primary_location_placeholder": "Adresse principale ou ville",
    "sub_locations_label": "Sous-lieux (ex: Etage 1, Batiment A)",
    "sub_location_add_placeholder": "Ajouter un sous-lieu...",
    "creating_parsing": "Création & Analyse...",
    "create_project_parse": "Créer le Projet & Analyser le Budget",
    "site_manager_label": "Conducteur de Travaux *",
    "add_sub_location": "Ajouter un sous-lieu",
    "sub_locations": "Sous-lieux",
    "sub_location_label": "Sous-lieu",
    "sub_location_placeholder": "Ex: Bâtiment A, Étage 1",
    "click_to_select_xls": "Cliquez pour sélectionner un fichier Excel (.xls, .xlsx)",
    "budget_file_label": "Fichier de Métré / Budget",
    "initial_progress": "Avancement Initial",
    "already_done": "Déjà exécuté",
    "finalize_import": "Finaliser l'Importation",
    "pm_analytics": "Analyses (Chef de Projet)",
    "not_applicable": "N/A",
    "plan_for_week": "Planifier pour la semaine",
    "next_week_short": "S+1 (Prochaine)",
    "future_week_2": "S+2",
    "future_week_3": "S+3",
    "view_history": "Voir l'Historique",
    "plan_details": "Détails du Plan",
    "history": "Historique",
    "active_planned": "Actif & Planifié",
    "back_to_history": "Retour à l'Historique",
    "project_history": "Historique du Projet",
    "history_desc": "Consultez tous les rapports hebdomadaires passés et les planifications actives.",
    "submitted_reports": "Rapports Soumis",
    "no_history_yet": "Aucun historique disponible pour le moment.",
    "material_forecast_hint": "Prévisions basées sur le plan :",
    "types_of_materials": "types de matériaux",
    "current": "Actuelle",
    "readiness_checklist": "Liste de préparation",
    "detailed_task_breakdown": "Détails des tâches",
    "visual_proof": "Preuves visuelles",
    "total_hrs_avail": "Toutes heures dispos",
    "productivity": "Productivité",
    "workforce": "Main d'œuvre",
    "persons": "personnes",
    "hero_title_1": "Maîtrise la",
    "hero_title_2": "planification",
    "hero_subtitle": "Plateforme SaaS de gestion de projet de construction de nouvelle génération. Optimisez vos ressources et vos délais avec précision.",
    "cta_button": "Commencer maintenant",
    "feature_analytics_title": "Données & Analytics",
    "feature_analytics_subtitle": "Pilotez vos chantiers avec des données en temps réel",
    "feature_analytics_desc": "Tableaux de bord interactifs, analyses prédictives et suivi de la productivité. Visualisez l'avancement de chaque projet, identifiez les écarts et prenez des décisions basées sur des données fiables.",
    "feature_analytics_cta": "Voir les analyses",
    "feature_analytics_item_1": "KPIs en temps réel",
    "feature_analytics_item_2": "Earned Value Management",
    "feature_analytics_item_3": "Analyses de causes (RCA)",
    "feature_analytics_item_4": "Comparaison inter-chantiers",
    "feature_workforce_title": "Gestion des Équipes",
    "feature_workforce_subtitle": "Organisez votre main-d'œuvre avec précision",
    "feature_workforce_desc": "Planification hebdomadaire, assignation des tâches par localisation, suivi des disponibilités et gestion des sous-traitants. Tout en un seul endroit.",
    "feature_workforce_cta": "Gérer les équipes",
    "feature_workforce_item_1": "Planification S+1, S+2, S+3",
    "feature_workforce_item_2": "Assignation par zone",
    "feature_workforce_item_3": "Suivi des sous-traitants",
    "feature_workforce_item_4": "Rapports journaliers",
    "feature_compliance_title": "Conformité & Contrôle",
    "feature_compliance_subtitle": "Garantissez la qualité à chaque étape",
    "feature_compliance_desc": "Checklists de validation, rapports de conformité automatisés, preuves visuelles et traçabilité complète. Assurez le respect des normes sur chaque chantier.",
    "feature_compliance_cta": "Voir les contrôles",
    "feature_compliance_item_1": "Checklists de validation",
    "feature_compliance_item_2": "Preuves visuelles",
    "feature_compliance_item_3": "Rapports automatisés",
    "feature_compliance_item_4": "Traçabilité complète",
    "stat_active_projects": "Projets actifs",
    "stat_teams_deployed": "Équipes déployées",
    "stat_compliance": "Conformité",
    "dashboard_label": "Dashboard — Vue d'ensemble",
    "footer_cta_title": "Prêt à transformer vos chantiers ?",
    "footer_cta_desc": "Rejoignez les équipes qui optimisent leur productivité avec EEG.",
    "explore": "Explorer",
    "health_planning": "Planification",
    "health_feedback": "Retour d'info",
    "health_efficiency": "Efficience",
    "health_good": "Bon",
    "health_average": "Moyen",
    "health_poor": "Insuffisant",
    "back_to_project": "Retour au Projet",
    "drawings_ready": "Plans Prêts",
    "materials_onsite": "Matériaux sur Site",
    "tools_ready": "Outils Prêts",
    "sub_ready": "Sous-traitants Prêts",
    "no_issues_reported": "Aucun problème signalé pour cette semaine.",
    "no_location": "Aucune localisation spécifiée",
    "status": "Statut",
    "achieved_hours": "Heures Réalisées",
    "planned_hours": "Heures Planifiées",
    "burned_hours_ac": "Heures Brûlées (AC)",
    "earned_value_ev": "Valeur Acquise (EV)",
    "planned_value_pv": "Valeur Planifiée (PV)",
    "admin_dashboard": "Panneau d'Administration",
    "admin_dashboard_desc": "EEG Management — Vue globale",
    "close_week": "Clôture Semaine",
    "logout": "Déconnexion",
    "week_closed": "Clôture effectuée.",
    "auto_close_error": "Erreur lors de la clôture automatique.",
    "action_error": "Erreur lors de l'action.",
    "projects": "Projets",
    "closed_plans": "Plans clôturés",
    "target_rate": "Taux objectif",
    "global_labor_hours": "Heures MO Global",
    "achieved_value": "Valorisé",
    "budget": "Budget",
    "pct_achieved": "% valorisé",
    "profitability": "Rentabilité",
    "target_hit_rate": "% taux d'objectifs atteints",
    "labor_budget": "Budget MO",
    "progress": "Avancement",
    "targets": "Objectifs",
    "pending": "En Attente",
    "back_to_dashboard": "Retour au tableau de bord",
    "future_week_1": "S+1",
    "no_pending_requests": "Aucune demande en attente.",
    "no_name": "Sans Nom",
    "reject": "Refuser",
    "approve": "Approuver",
    "personnel_ranking": "Classement du Personnel",
    "no_processed_users": "Aucun utilisateur traité.",
    "rank": "Rang",
    "adventurer": "Aventurier",
    "identity": "Identité",
    "role": "Rôle",
    "level": "Niveau",
    "admin_status": "Statut",
    "approved": "Approuvé",
    "rejected": "Refusé",
    "admin_loading": "Chargement de l'administration...",
    "daily_report_subtitle": "Personnel · Heures · Avancement",
    "planning_title": "Planification",
    "planning_subtitle": "S+1 · S+2 · S+3",
    "history_title": "Historique",
    "history_subtitle": "Rapports des semaines clôturées",
    "closed_weeks_badge": "SEMAINES CLÔTURÉES",
    "labor_progress": "Avancement MO",
    "labor_hours": "Heures MO",
    "workload": "Charge (H)",
    "nodes_pl": "Nœuds",
    "load": "Charge",
    "download_template": "Télécharger le Modèle Excel",
    "add_zones_first": "Ajoutez d'abord des sous-lieux (zones) avant de télécharger le modèle.",
    "remove": "Supprimer",
    "continue": "Continuer",
    "description": "Description"
  },
  en: {
    "login": "Login",
    "get_started": "Get Started",
    "dashboard": "Dashboard",
    "unassigned": "Unassigned",
    "back_to_dashboard": "Back to Dashboard",
    "future_week_1": "S+1",
    "global_budget_progress": "Global Budget Progress",
    "total_scheduled_labor": "Total Scheduled Labor",
    "achieved_labor_value": "Achieved Labor Value",
    "tasks_tracked": "Tasks Tracked",
    "completed": "Completed",
    "weekly_reports": "Weekly Reports",
    "no_weekly_reports": "The Site Manager has not submitted any weekly plans or reports yet.",
    "week": "Week",
    "workers_setup": "Workers Setup",
    "total_hrs": "total hrs",
    "in_progress": "In Progress",
    "target_hit": "Target Hit",
    "target_missed": "Target Missed",
    "reported_issues": "Reported Issues",
    "no_issues": "No issues reported.",
    "scheduled_tasks": "Scheduled Tasks",
    "planned": "Planned",
    "done": "Done",
    "active_projects": "Active Projects",
    "submitted_plans": "Submitted Weekly Plans",
    "your_sites": "Your Sites",
    "site_manager": "Site Manager",
    "location": "Location",
    "tasks_loaded": "Loaded Tasks",
    "view_details": "View Details",
    "delete": "Delete",
    "no_projects": "No projects configured yet.",
    "new_project": "New Project (Excel Upload)",
    "upload_in_progress": "Uploading...",
    "global_progress": "Global Progress",
    "efficiency_progression": "Efficiency Progression",
    "hour_distribution": "Hour Distribution",
    "all_weeks": "All weeks",
    "weeks_4": "4 Weeks",
    "weeks_8": "8 Weeks",
    "weeks_12": "12 Weeks",
    "executed": "Executed",
    "display": "Display",
    "welcome": "Welcome",
    "hours": "h",
    "special_works": "SPECIAL TECHNICAL WORKS",
    "category": "Category",
    "unit": "Unit",
    "quantity": "Quantity",
    "cable": "Cable",
    "tube": "Conduit",
    "lighting": "Lighting",
    "primary_pipes": "Primary pipes",
    "electrical_panels": "Electrical panels",
    "others": "Others",
    "last_revision": "Last revision",
    "created": "created",
    "updated": "updated",
    "cancelled": "cancelled",
    "empty_drums": "Empty drums (Consignations) to pickup",
    "category_heatmap": "Category Productivity (Heatmap)",
    "efficiency_delta": "Category Efficiency (%)",
    "missed_reason_select": "Missed Target Reason",
    "MATERIAL_DELAY": "Material Delay",
    "WEATHER": "Weather",
    "EQUIPMENT_FAILURE": "Equipment Failure",
    "LABOR_SHORTAGE": "Labor Shortage",
    "PLANNING_ERROR": "Planning Error",
    "OTHER": "Other",
    "user_not_found": "User not found",
    "global_status": "Global Status",
    "active_sites": "Active Sites",
    "total_tasks": "Total Tasks",
    "assigned_tasks": "Assigned tasks",
    "on_site": "On site",
    "view_analytics": "View Analytics",
    "enter_daily_report": "Enter daily report",
    "view_planning": "View planning",
    "manage_teams": "Manage teams",
    "no_assigned_sites": "You are not assigned to any site at the moment.",
    "contact_pm": "Please contact your Project Manager.",
    "recent_alerts": "Recent Alerts",
    "offline_sync_pending": "Offline sync pending",
    "offline_sync_reports": "reports",
    "connect_to_network": "Connect to the network.",
    "check": "Check",
    "sm_analytics_title": "Analytics (Site Manager)",
    "my_statistics": "My Statistics",
    "statistics_overview": "Overview of the progress of your assigned sites.",
    "projects_progress_hours": "Projects Progress (Hours)",
    "benchmarking_title": "Cross-Site Benchmarking",
    "benchmarking_desc": "Compare the overall efficiency of your sites with the rest of the fleet (anonymized).",
    "back": "Back",
    "loading": "Loading...",
    "plan_next_week_title": "Plan Next Week",
    "plan_next_week_desc": "Define your workforce and select tasks with their locations.",
    "workforce_availability": "Workforce Availability",
    "available_workers_count": "Available workers count",
    "target_100": "Target (100%)",
    "tasks_catalog": "Tasks Catalog",
    "uncategorized": "Uncategorized",
    "lines_pl": "lines",
    "remaining_pl": "remaining",
    "back_to_categories": "Back to Categories",
    "search_in": "Search in",
    "remaining_label": "Remaining:",
    "remaining": "Remaining",
    "line_label": "Line",
    "remains": "Remains",
    "add_to_plan": "Add to Plan",
    "weekly_cart": "Weekly Cart",
    "currently_planned": "Currently Planned:",
    "empty_plan_msg": "Your plan is empty. Add tasks from the catalog.",
    "qty_to_do": "Qty to do:",
    "locations_up_to_4": "Locations (up to 4 dropdowns):",
    "none": "-- None --",
    "materials_forecast": "Materials Forecast",
    "validation_checklist": "Validation Checklist",
    "ready": "Ready",
    "materials_ok": "Materials OK",
    "tools_ok": "Tools OK",
    "subcontractors": "Subcontractors",
    "validate_and_save_plan": "Validate and Save Plan",
    "network_restored": "Network restored. Reports synced successfully.",
    "offline_mode_detected": "Offline mode detected. Saved locally.",
    "checking_db": "Checking database...",
    "no_active_plan": "No Active Plan",
    "no_active_plan_desc": "You have no active plan scheduled for this project this week.",
    "daily_report_title": "Daily Report",
    "offline_badge": "OFFLINE",
    "daily_report_desc": "Field validations, photos, and entry of achieved targets.",
    "planned_target": "Planned Target",
    "achieved": "Achieved",
    "recorded_activity": "Recorded Activity",
    "planned_qty_var": "Planned: ",
    "execution_locations": "Execution locations:",
    "issues_observations": "Issues & Observations",
    "target_missed_categorize": "Target not met. Please categorize the cause:",
    "select_rca_cause": "-- Select a cause (RCA) --",
    "detailed_desc_optional": "Detailed description (Optional):",
    "workforce_count_label": "Workforce Size",
    "workforce_count_desc": "Indicate the number of workers present today.",
    "add_unplanned_task": "Add Unplanned Task",
    "select_category": "Select a category",
    "select_task": "Select a task",
    "add_btn": "Add",
    "non_planifie_badge": "Unplanned",
    "problem_details_placeholder": "Problem details (e.g., missing material on floor 2)...",
    "empty_drums_title": "Empty Drums (Consignations)",
    "empty_drums_desc": "Indicate the empty cable drums ready for pickup.",
    "empty_drums_label": "Empty drums:",
    "cancel": "Cancel",
    "save_locally": "Save Locally",
    "submit_report": "Submit Report",
    "project_manager": "Project Manager",
    "supervision_desc": "Supervision of all installations, site teams and budget tracking.",
    "upload_xls": "Upload XLS Plan",
    "alerts_count": "alerts",
    "portfolio_performance": "Portfolio Performance",
    "portfolio_analysis_desc": "In-depth analysis of productivity and delay causes across all your sites.",
    "overall_efficiency": "Overall Efficiency",
    "ratio_actual_planned": "Actual vs Planned ratio",
    "cumulative_value": "Cumulative value",
    "reported_rca": "Reported RCA",
    "categorized_deviations": "Categorized deviations",
    "under_your_supervision": "Under your supervision",
    "projects_progress_pm": "Project Progression",
    "progress_comparison_desc": "Comparison of planned vs executed hours.",
    "efficiency_by_category": "Efficiency by Business Category",
    "cross_project_analysis_desc": "Cross-project productivity analysis.",
    "evm_desc": "Cumulative evolution of planned value (PV), earned value (EV) and burned hours (AC).",
    "no_evm_data": "No EVM data available.",
    "rca_analysis": "Root Cause Analysis (RCA)",
    "recent_field_reports": "Recent Field Reports",
    "no_recent_issues": "No issues reported recently.",
    "evm_title": "Earned Value Management (EVM)",
    "rca_title": "Root Cause Analysis (RCA)",
    "recent_reports_title": "Recent Field Reports",
    "project_field": "Project:",
    "no_evm_data_available": "No EVM data available.",
    "upload_xls_title": "Create New Project & Upload Budget",
    "upload_xls_desc": "Fill out the project details and upload the 'Bordereau de prix' Excel file to generate the task list.",
    "success_project_created": "Successfully Created Project!",
    "parsing_redirect": "Parsed data and redirecting back to dashboard...",
    "project_name_label": "Project Name *",
    "project_name_placeholder": "e.g. Office Complex",
    "site_manager_placeholder": "Select a Site Manager",
    "start_date_label": "Start Date",
    "end_date_label": "End Date",
    "primary_location_label": "Primary Location",
    "primary_location_placeholder": "Main address or city",
    "sub_locations_label": "Sub-locations (e.g. Floor 1, Building A)",
    "sub_location_add_placeholder": "Add a sub-location...",
    "creating_parsing": "Creating & Parsing...",
    "create_project_parse": "Create Project & Parse Budget",
    "site_manager_label": "Site Manager *",
    "add_sub_location": "Add sub-location",
    "sub_locations": "Sub-locations",
    "sub_location_label": "Sub-location",
    "sub_location_placeholder": "e.g. Building A, Floor 1",
    "click_to_select_xls": "Click to select Excel file (.xls, .xlsx)",
    "budget_file_label": "Métré / Budget File",
    "initial_progress": "Initial Progress",
    "already_done": "Already done",
    "finalize_import": "Finalize Import",
    "pm_analytics": "Analytics (Project Manager)",
    "not_applicable": "N/A",
    "plan_for_week": "Plan for week",
    "next_week_short": "S+1 (Next)",
    "future_week_2": "S+2",
    "future_week_3": "S+3",
    "view_history": "View History",
    "plan_details": "Plan Details",
    "history": "History",
    "active_planned": "Active & Planned",
    "back_to_history": "Back to History",
    "project_history": "Project History",
    "history_desc": "Review all past weekly reports and active plans.",
    "submitted_reports": "Submitted Reports",
    "no_history_yet": "No history available yet.",
    "material_forecast_hint": "Forecast based on plan:",
    "types_of_materials": "types of materials",
    "current": "Current",
    "readiness_checklist": "Readiness Checklist",
    "detailed_task_breakdown": "Detailed Task Breakdown",
    "visual_proof": "Visual Proof",
    "total_hrs_avail": "total hrs available",
    "productivity": "Productivity",
    "workforce": "Workforce",
    "persons": "persons",
    "hero_title_1": "Master your",
    "hero_title_2": "planning",
    "hero_subtitle": "Next-generation SaaS platform for construction project management. Optimize your resources and timelines with precision.",
    "cta_button": "Get started",
    "feature_analytics_title": "Data & Analytics",
    "feature_analytics_subtitle": "Drive your sites with real-time data",
    "feature_analytics_desc": "Interactive dashboards, predictive analytics and productivity tracking. Visualize progress on every project, identify gaps and make decisions based on reliable data.",
    "feature_analytics_cta": "View analytics",
    "feature_analytics_item_1": "Real-time KPIs",
    "feature_analytics_item_2": "Earned Value Management",
    "feature_analytics_item_3": "Root Cause Analysis (RCA)",
    "feature_analytics_item_4": "Cross-site benchmarking",
    "feature_workforce_title": "Team Management",
    "feature_workforce_subtitle": "Organize your workforce with precision",
    "feature_workforce_desc": "Weekly planning, task assignment by location, availability tracking and subcontractor management. All in one place.",
    "feature_workforce_cta": "Manage teams",
    "feature_workforce_item_1": "Planning S+1, S+2, S+3",
    "feature_workforce_item_2": "Zone-based assignment",
    "feature_workforce_item_3": "Subcontractor tracking",
    "feature_workforce_item_4": "Daily reports",
    "feature_compliance_title": "Compliance & Control",
    "feature_compliance_subtitle": "Ensure quality at every step",
    "feature_compliance_desc": "Validation checklists, automated compliance reports, visual proof and full traceability. Ensure standards are met on every site.",
    "feature_compliance_cta": "View controls",
    "feature_compliance_item_1": "Validation checklists",
    "feature_compliance_item_2": "Visual proof",
    "feature_compliance_item_3": "Automated reports",
    "feature_compliance_item_4": "Full traceability",
    "stat_active_projects": "Active projects",
    "stat_teams_deployed": "Teams deployed",
    "stat_compliance": "Compliance",
    "dashboard_label": "Dashboard — Overview",
    "footer_cta_title": "Ready to transform your sites?",
    "footer_cta_desc": "Join the teams optimizing their productivity with EEG.",
    "explore": "Explore",
    "health_planning": "Planning",
    "health_feedback": "Feedback",
    "health_efficiency": "Efficiency",
    "health_good": "Good",
    "health_average": "Average",
    "health_poor": "Poor",
    "back_to_project": "Back to Project",
    "drawings_ready": "Drawings Ready",
    "materials_onsite": "Materials On-site",
    "tools_ready": "Tools Ready",
    "sub_ready": "Subcontractors Ready",
    "no_issues_reported": "No issues reported for this week.",
    "no_location": "No location specified",
    "status": "Status",
    "achieved_hours": "Achieved Hours",
    "planned_hours": "Planned Hours",
    "burned_hours_ac": "Burned Hours (AC)",
    "earned_value_ev": "Earned Value (EV)",
    "planned_value_pv": "Planned Value (PV)",
    "admin_dashboard": "Administration Panel",
    "admin_dashboard_desc": "EEG Management — Global View",
    "close_week": "Close Week",
    "logout": "Logout",
    "week_closed": "Weekly closure completed.",
    "auto_close_error": "Error during automatic closure.",
    "action_error": "Error during action.",
    "projects": "Projects",
    "closed_plans": "Closed Plans",
    "target_rate": "Target Rate",
    "global_labor_hours": "Global Labor Hours",
    "achieved_value": "Achieved",
    "budget": "Budget",
    "pct_achieved": "% achieved",
    "profitability": "Profitability",
    "target_hit_rate": "% target hit rate",
    "labor_budget": "Labor Budget",
    "progress": "Progress",
    "targets": "Targets",
    "pending": "Pending",
    "no_pending_requests": "No pending requests.",
    "no_name": "No Name",
    "reject": "Reject",
    "approve": "Approve",
    "personnel_ranking": "Personnel Ranking",
    "no_processed_users": "No processed users.",
    "rank": "Rank",
    "adventurer": "Adventurer",
    "identity": "Identity",
    "role": "Role",
    "level": "Level",
    "admin_status": "Status",
    "approved": "Approved",
    "rejected": "Rejected",
    "admin_loading": "Loading administration...",
    "daily_report_subtitle": "Personnel · Hours · Progress",
    "planning_title": "Planning",
    "planning_subtitle": "S+1 · S+2 · S+3",
    "history_title": "History",
    "history_subtitle": "Reports of closed weeks",
    "closed_weeks_badge": "CLOSED WEEKS",
    "labor_progress": "Labor Progress",
    "labor_hours": "Labor Hours",
    "workload": "Workload",
    "nodes_pl": "Nodes",
    "load": "Load",
    "download_template": "Download Excel Template",
    "add_zones_first": "Add sub-locations (zones) first before downloading the template.",
    "remove": "Remove",
    "continue": "Continue",
    "description": "Description"
  },
  nl: {
    "login": "Inloggen",
    "get_started": "Starten",
    "dashboard": "Dashboard",
    "unassigned": "Niet toegewezen",
    "back_to_dashboard": "Terug naar Dashboard",
    "future_week_1": "S+1",
    "global_budget_progress": "Globale Budgetvoortgang",
    "total_scheduled_labor": "Geplande Arbeidsuren",
    "achieved_labor_value": "Gerealiseerde Arbeidsuren",
    "tasks_tracked": "Opgevolgde Taken",
    "completed": "Voltooid",
    "weekly_reports": "Wekelijkse Rapporten",
    "no_weekly_reports": "De werfleider heeft nog geen wekelijkse plannen of rapporten ingediend.",
    "week": "Week",
    "workers_setup": "Team",
    "total_hrs": "totaal uren",
    "in_progress": "In uitvoering",
    "target_hit": "Doel Bereikt",
    "target_missed": "Doel Gemist",
    "reported_issues": "Gemelde Problemen",
    "no_issues": "Geen problemen gemeld.",
    "scheduled_tasks": "Geplande Taken",
    "planned": "Gepland",
    "done": "Uitgevoerd",
    "active_projects": "Actieve Projecten",
    "submitted_plans": "Ingediende Weekplannen",
    "your_sites": "Uw Werven",
    "site_manager": "Werfleider",
    "location": "Locatie",
    "tasks_loaded": "Geladen Taken",
    "view_details": "Details Bekijken",
    "delete": "Verwijderen",
    "no_projects": "Nog geen projecten geconfigureerd.",
    "new_project": "Nieuw Project (Excel Upload)",
    "budget_file_label": "Meetstaat / Budgetbestand",
    "initial_progress": "Initiële Voortgang",
    "already_done": "Reeds uitgevoerd",
    "finalize_import": "Import Afronden",
    "upload_in_progress": "Uploaden...",
    "global_progress": "Globale Voortgang",
    "efficiency_progression": "Efficiëntie Voortgang",
    "hour_distribution": "Urenverdeling",
    "all_weeks": "Alle weken",
    "weeks_4": "4 Weken",
    "weeks_8": "8 Weken",
    "weeks_12": "12 Weken",
    "executed": "Uitgevoerd",
    "display": "Weergave",
    "welcome": "Welkom",
    "hours": "u",
    "special_works": "SPECIALE TECHNISCHE WERKEN",
    "category": "Categorie",
    "unit": "Eenheid",
    "quantity": "Hoeveelheid",
    "cable": "Kabel",
    "tube": "Wachtbuis",
    "lighting": "Verlichting",
    "primary_pipes": "Primaire leidingen",
    "electrical_panels": "Elektrische panelen",
    "others": "Andere",
    "last_revision": "Laatste revisie",
    "created": "aangemaakt",
    "updated": "bijgewerkt",
    "cancelled": "geannuleerd",
    "empty_drums": "Tourets vides (Consignations) à récupérer",
    "category_heatmap": "Category Productivity (Heatmap)",
    "efficiency_delta": "Category Efficiency (%)",
    "missed_reason_select": "Missed Target Reason",
    "MATERIAL_DELAY": "Materiaalvertraging",
    "WEATHER": "Weer",
    "EQUIPMENT_FAILURE": "Apparatuurdefect",
    "LABOR_SHORTAGE": "Tekort aan arbeid",
    "PLANNING_ERROR": "Planningsfout",
    "OTHER": "Ander",
    "user_not_found": "Gebruiker niet gevonden",
    "global_status": "Globale Statut",
    "active_sites": "Actieve werven",
    "total_tasks": "Totaal aantal taken",
    "assigned_tasks": "Toegewezen taken",
    "on_site": "Op site",
    "view_analytics": "Zie Analyses",
    "enter_daily_report": "Dagelijks rapport invoeren",
    "view_planning": "Planning bekijken",
    "manage_teams": "Teams beheren",
    "no_assigned_sites": "U bent momenteel niet toegewezen aan een site.",
    "contact_pm": "Neem contact op met je Project Manager.",
    "recent_alerts": "Recente waarschuwingen",
    "offline_sync_pending": "Offline synchronisatie in afwachting",
    "offline_sync_reports": "rapporten",
    "connect_to_network": "Maak verbinding met het netwerk.",
    "check": "Check",
    "sm_analytics_title": "Analytics (Werfleider)",
    "my_statistics": "Mijn Statistieken",
    "statistics_overview": "Overzicht van de voortgang van uw toegewezen werven.",
    "projects_progress_hours": "Voortgang Projecten (Uren)",
    "benchmarking_title": "Cross-Site Benchmarking",
    "benchmarking_desc": "Vergelijk de globale efficiëntie van uw werven met de rest van het park (geanonimiseerd).",
    "back": "Terug",
    "loading": "Laden...",
    "plan_next_week_title": "Plan volgende week",
    "plan_next_week_desc": "Definieer uw personeelsbestand en selecteer taken met hun locaties.",
    "workforce_availability": "Beschikbaarheid van personeel",
    "available_workers_count": "Aantal beschikbare werknemers",
    "target_100": "Doel (100%)",
    "tasks_catalog": "Takenoverzicht",
    "uncategorized": "Niet gecategoriseerd",
    "lines_pl": "lijnen",
    "remaining_pl": "overblijvend",
    "back_to_categories": "Terug naar Categorieën",
    "search_in": "Zoek in",
    "remaining_label": "Overblijvend:",
    "remaining": "Overblijvend",
    "line_label": "Lijn",
    "remains": "Blijft over",
    "add_to_plan": "Voeg toe aan plan",
    "weekly_cart": "Wekelijkse mandje",
    "currently_planned": "Momenteel Gepland:",
    "empty_plan_msg": "Uw plan is leeg. Voeg taken toe uit de catalogus.",
    "qty_to_do": "Hoeveelheid te doen:",
    "locations_up_to_4": "Locaties (tot 4 dropdowns):",
    "none": "-- Geen --",
    "materials_forecast": "Materiaalvoorspelling",
    "validation_checklist": "Validatie Checklist",
    "ready": "Gereed",
    "materials_ok": "Materialen OK",
    "tools_ok": "Gereedschap OK",
    "subcontractors": "Onderaannemers",
    "validate_and_save_plan": "Plan valideren en opslaan",
    "network_restored": "Netwerk hersteld. Rapporten succesvol gesynchroniseerd.",
    "offline_mode_detected": "Offline-modus gedetecteerd. Lokaal opgeslagen.",
    "checking_db": "Database controleren...",
    "no_active_plan": "Geen actief plan",
    "no_active_plan_desc": "U heeft deze week geen actief plan gepland voor dit project.",
    "daily_report_title": "Dagelijks Rapport",
    "offline_badge": "OFFLINE",
    "daily_report_desc": "Veldvalidaties, foto's en invoer van behaalde doelen.",
    "planned_target": "Gepland Doel",
    "achieved": "Behaald",
    "recorded_activity": "Geregistreerde Activiteit",
    "planned_qty_var": "Gepland: ",
    "execution_locations": "Executie locaties:",
    "issues_observations": "Problemen & Observaties",
    "target_missed_categorize": "Doel niet behaald. Categoriseer de oorzaak:",
    "select_rca_cause": "-- Selecteer een oorzaak (RCA) --",
    "detailed_desc_optional": "Gedetailleerde beschrijving (optioneel):",
    "workforce_count_label": "Aantal werknemers",
    "workforce_count_desc": "Geef het aantal aanwezige werknemers voor vandaag op.",
    "add_unplanned_task": "Ongeplande taak toevoegen",
    "select_category": "Selecteer een categorie",
    "select_task": "Selecteer een taak",
    "add_btn": "Toevoegen",
    "non_planifie_badge": "Ongepland",
    "problem_details_placeholder": "Details van het probleem (bijv. ontbrekend materiaal op verdieping 2)...",
    "empty_drums_title": "Lege Rollen (Consignations)",
    "empty_drums_desc": "Geef de lege kabelrollen aan die klaar zijn voor ophaling.",
    "empty_drums_label": "Lege rollen:",
    "cancel": "Annuleren",
    "save_locally": "Lokaal Opslaan",
    "submit_report": "Rapport Indienen",
    "project_manager": "Project Manager",
    "supervision_desc": "Toezicht op alle installaties, werfteams en budgetopvolging.",
    "upload_xls": "XLS Plan Uploaden",
    "alerts_count": "waarschuwingen",
    "portfolio_performance": "Portfolio Prestaties",
    "portfolio_analysis_desc": "Diepgaande analyse van productiviteit en vertragingsoorzaken op al uw werven.",
    "overall_efficiency": "Globale Efficiëntie",
    "ratio_actual_planned": "Gerealiseerd vs Gepland ratio",
    "cumulative_value": "Cumulatieve waarde",
    "reported_rca": "Gerapporteerde RCA",
    "categorized_deviations": "Gecategoriseerde afwijkingen",
    "under_your_supervision": "Onder uw toezicht",
    "projects_progress_pm": "Projectvoortgang",
    "progress_comparison_desc": "Vergelijking van geplande vs uitgevoerde uren.",
    "efficiency_by_category": "Efficiëntie per Bedrijfscategorie",
    "cross_project_analysis_desc": "Voortgangsanalyse over projecten heen.",
    "evm_desc": "Cumulatieve evolutie van geplande waarde (PV), behaalde waarde (EV) en gemaakte uren (AC).",
    "no_evm_data": "Geen EVM-gegevens beschikbaar.",
    "rca_analysis": "Oorzaakanalyse (RCA)",
    "recent_field_reports": "Recente Veldrapporten",
    "no_recent_issues": "Geen problemen onlangs gemeld.",
    "evm_title": "Earned Value Management (EVM)",
    "rca_title": "Oorzaakanalyse (RCA)",
    "recent_reports_title": "Recente Veldrapporten",
    "project_field": "Project:",
    "no_evm_data_available": "Geen EVM-gegevens beschikbaar.",
    "upload_xls_title": "Nieuw Project Aanmaken & Budget Uploaden",
    "upload_xls_desc": "Vul de projectdetails in en upload het 'Bordereau de prix' Excel-bestand om de takenlijst te genereren.",
    "success_project_created": "Project succesvol aangemaakt!",
    "parsing_redirect": "Gegevens verwerkt en terugkeren naar dashboard...",
    "project_name_label": "Projectnaam *",
    "project_name_placeholder": "bijv. Kantorencomplex",
    "site_manager_placeholder": "Selecteer een Werfleider",
    "start_date_label": "Startdatum",
    "end_date_label": "Einddatum",
    "primary_location_label": "Hoofdlocatie",
    "primary_location_placeholder": "Hoofdadres of stad",
    "sub_locations_label": "Sublocaties (bijv. Verdieping 1, Gebouw A)",
    "sub_location_add_placeholder": "Sublocatie toevoegen...",
    "creating_parsing": "Aanmaken & Verwerken...",
    "create_project_parse": "Project Aanmaken & Budget Verwerken",
    "site_manager_label": "Werfleider *",
    "add_sub_location": "Sublocatie toevoegen",
    "pm_analytics": "Analytics (Project Manager)",
    "not_applicable": "N/A",
    "plan_for_week": "Plan voor week",
    "next_week_short": "S+1 (Volgende)",
    "future_week_2": "S+2",
    "future_week_3": "S+3",
    "view_history": "Geschiedenis bekijken",
    "plan_details": "Plandetails",
    "history": "Geschiedenis",
    "active_planned": "Actief & Gepland",
    "back_to_history": "Terug naar Geschiedenis",
    "project_history": "Projectgeschiedenis",
    "history_desc": "Bekijk alle eerdere wekelijkse rapporten en actieve plannen.",
    "submitted_reports": "Ingediende Rapporten",
    "no_history_yet": "Nog geen geschiedenis beschikbaar.",
    "material_forecast_hint": "Voorspelling op basis van plan:",
    "types_of_materials": "soorten materialen",
    "current": "Huidige",
    "readiness_checklist": "Gereedheidschecklist",
    "detailed_task_breakdown": "Gedetailleerde takenlijst",
    "visual_proof": "Visueel bewijs",
    "total_hrs_avail": "totaal uren beschikbaar",
    "productivity": "Productiviteit",
    "workforce": "Personeel",
    "persons": "personen",
    "hero_title_1": "Beheers uw",
    "hero_title_2": "planning",
    "hero_subtitle": "Next-generation SaaS-platform voor bouwprojectbeheer. Optimaliseer uw middelen en tijdlijnen met precisie.",
    "cta_button": "Aan de slag",
    "feature_analytics_title": "Data & Analytics",
    "feature_analytics_subtitle": "Beheer uw werven met real-time data",
    "feature_analytics_desc": "Interactieve dashboards, voorspellende analyses en productiviteitsopvolging. Visualiseer de voortgang van elk project, identificeer hiaten en neem beslissingen op basis van betrouwbare data.",
    "feature_analytics_cta": "Analyses bekijken",
    "feature_analytics_item_1": "Real-time KPI's",
    "feature_analytics_item_2": "Earned Value Management",
    "feature_analytics_item_3": "Oorzaakanalyse (RCA)",
    "feature_analytics_item_4": "Cross-site benchmarking",
    "feature_workforce_title": "Teambeheer",
    "feature_workforce_subtitle": "Organiseer uw personeel met precisie",
    "feature_workforce_desc": "Wekelijkse planning, taaktoewijzing per locatie, beschikbaarheidsopvolging en onderaannemersbeheer. Alles op één plek.",
    "feature_workforce_cta": "Teams beheren",
    "feature_workforce_item_1": "Planning S+1, S+2, S+3",
    "feature_workforce_item_2": "Zonegebaseerde toewijzing",
    "feature_workforce_item_3": "Onderaannemers opvolgen",
    "feature_workforce_item_4": "Dagelijkse rapporten",
    "feature_compliance_title": "Compliantie & Controle",
    "feature_compliance_subtitle": "Garandeer kwaliteit bij elke stap",
    "feature_compliance_desc": "Validatiechecklists, geautomatiseerde complianterapporten, visueel bewijs en volledige traceerbaarheid. Zorg ervoor dat de normen op elke werf worden nageleefd.",
    "feature_compliance_cta": "Controles bekijken",
    "feature_compliance_item_1": "Validatiechecklists",
    "feature_compliance_item_2": "Visueel bewijs",
    "feature_compliance_item_3": "Geautomatiseerde rapporten",
    "feature_compliance_item_4": "Volledige traceerbaarheid",
    "stat_active_projects": "Actieve projecten",
    "stat_teams_deployed": "Teams ingezet",
    "stat_compliance": "Compliantie",
    "dashboard_label": "Dashboard — Overzicht",
    "footer_cta_title": "Klaar om uw werven te transformeren?",
    "footer_cta_desc": "Sluit u aan bij de teams die hun productiviteit optimaliseren met EEG.",
    "explore": "Verkennen",
    "health_planning": "Planning",
    "health_feedback": "Feedback",
    "health_efficiency": "Efficiëntie",
    "health_good": "Goed",
    "health_average": "Gemiddeld",
    "health_poor": "Slecht",
    "back_to_project": "Terug naar Project",
    "drawings_ready": "Tekeningen Gereed",
    "materials_onsite": "Materialen op Site",
    "tools_ready": "Gereedschap Gereed",
    "sub_ready": "Onderaannemers Gereed",
    "no_issues_reported": "Geen problemen gerapporteerd voor deze week.",
    "no_location": "Geen locatie opgegeven",
    "status": "Status",
    "achieved_hours": "Behaalde Uren",
    "planned_hours": "Geplande Uren",
    "burned_hours_ac": "Gemaakte Uren (AC)",
    "earned_value_ev": "Verdiende Waarde (EV)",
    "planned_value_pv": "Geplande Waarde (PV)",
    "admin_dashboard": "Administratiepaneel",
    "admin_dashboard_desc": "EEG Management — Globaal Overzicht",
    "close_week": "Week Afsluiten",
    "logout": "Uitloggen",
    "week_closed": "Weekafsluiting voltooid.",
    "auto_close_error": "Fout bij automatische afsluiting.",
    "action_error": "Fout bij actie.",
    "projects": "Projecten",
    "closed_plans": "Afgesloten Plannen",
    "target_rate": "Doelpercentage",
    "global_labor_hours": "Globale Arbeidsuren",
    "achieved_value": "Gerealiseerd",
    "budget": "Budget",
    "pct_achieved": "% gerealiseerd",
    "profitability": "Winstgevendheid",
    "target_hit_rate": "% behaalde doelen",
    "labor_budget": "Arbeidsbudget",
    "progress": "Voortgang",
    "targets": "Doelstellingen",
    "pending": "In Afwachting",
    "no_pending_requests": "Geen openstaande verzoeken.",
    "no_name": "Zonder Naam",
    "reject": "Weigeren",
    "approve": "Goedkeuren",
    "personnel_ranking": "Personeelsrangschikking",
    "no_processed_users": "Geen verwerkte gebruikers.",
    "rank": "Rang",
    "adventurer": "Avonturier",
    "identity": "Identiteit",
    "role": "Rol",
    "level": "Niveau",
    "admin_status": "Status",
    "approved": "Goedgekeurd",
    "rejected": "Geweigerd",
    "admin_loading": "Administratie laden...",
    "daily_report_subtitle": "Personeel · Uren · Voortgang",
    "planning_title": "Planning",
    "planning_subtitle": "S+1 · S+2 · S+3",
    "history_title": "Geschiedenis",
    "history_subtitle": "Rapporten van afgesloten weken",
    "closed_weeks_badge": "AFGESLOTEN WEKEN",
    "labor_progress": "Voortgang Arbeid",
    "labor_hours": "Arbeidsuren",
    "workload": "Werklast",
    "nodes_pl": "Knooppunten",
    "load": "Belasting",
    "download_template": "Excel-sjabloon Downloaden",
    "add_zones_first": "Voeg eerst sublocaties (zones) toe voordat u het sjabloon downloadt.",
    "remove": "Verwijderen",
    "continue": "Doorgaan",
    "description": "Beschrijving"
  }
};

const dataTranslations: Record<Language, Record<string, string>> = {
  fr: {},
  en: {
    "Eclairage": "Lighting",
    "Canalisations primaires": "Primary Pipes",
    "Canalisations secondaires": "Secondary Pipes",
    "Tableaux électriques": "Electrical Panels",
    "Incendie": "Fire Safety",
    "Appareillage": "Switchgear",
    "Vidéo surveillance": "CCTV",
    "Câble": "Cable",
    "Câblage": "Cabling",
    "Tube d'attente": "Conduit",
    "Composant": "Component"
  },
  nl: {
    "Eclairage": "Verlichting",
    "Canalisations primaires": "Primaire leidingen",
    "Canalisations secondaires": "Secundaire leidingen",
    "Tableaux électriques": "Elektrische panelen",
    "Incendie": "Brandveiligheid",
    "Appareillage": "Schakelmateriaal",
    "Vidéo surveillance": "CCTV",
    "Câble": "Kabel",
    "Câblage": "Bekabeling",
    "Tube d'attente": "Wachtbuis",
    "Composant": "Component"
  }
};

interface LanguageContextProps {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  tData: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  lang: "fr",
  setLang: () => {},
  t: (k) => k,
  tData: (k) => k
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("fr");

  useEffect(() => {
    const saved = localStorage.getItem("app_lang") as Language;
    if (saved && ["fr", "en", "nl"].includes(saved)) {
      setTimeout(() => setLang(saved), 0);
    }
  }, []);

  const handleSetLang = (l: Language) => {
    setLang(l);
    localStorage.setItem("app_lang", l);
  };

  const t = (key: string): string => {
    return dictionaries[lang][key] || key;
  };

  const tData = (text: string): string => {
    if (!text) return text;
    return dataTranslations[lang][text] || text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, tData }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);

export const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899'];
